language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt

services:
  - mongodb

before_script:
  # Recommended by TravisCI before executing first command
  - sleep 15
  - "mongo mdg --eval 'db.users.insert({\"_id\" : ObjectId(\"5a1be8a34e87d517acc39652\"), \"verified\" : true, \"generated_count\" : 0, \"email\" : \"whocares@gmail.com\", \"last_used\" : ISODate(\"2017-12-16T00:59:37.318Z\")})'"

script: py.test tests/