#!/bin/bash
cdir=`dirname $0`
pdir=$PWD
echo "#######################################"
echo "Caution :"
echo "\"csv2xml\" has been renamed to \"csv2xml-cmd\""
echo "#######################################"
echo "calling csv2xml-cmd..."
echo " "
if [ -n $cdir ]; then
        tdir=$pdir
elif [ `echo $cdir | cut -b2` = './' ]; then
	tdir=$pdir"/"$cdir
else
	tdir=$cdir
fi
$tdir/c2x-cmd $@
